
# Environment Configuration

browser=chrome
implicitWait=10
headless=false


# Application URLs

adminPortalURL=https://stg.admin-garden.chdc.foxberry.live/
citizenPortalURL=https://stg.garden.chdc.foxberry.live/


# Role Credentials

superAdminMobile=8956009248
superAdminOTP=9999

adminMobile=9562341785
adminOTP=9999

operatorMobile=9852741632
operatorOTP=9999

citizenMobile=9767945710
citizenOTP=9999


# Framework Paths

testDataPath=src/test/resources/testdata/
screenshotPath=src/test/resources/screenshots/
reportPath=target/reports/
